import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

  export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>       

      <div className='bg-slate-400 p-2'>
        <h1 className='text-2xl font-bold'> Next Shop</h1>
        <p>Kim Dahyuk</p>
      </div>
    </div>
  )
}
